language: php

php:
  - 7.1
  - 7.2

install:
  - echo $hello
  - composer install -vvv --profile --prefer-dist

script:
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-text

notifications:
  email:
    recipients:
      - 36749952@qq.com
      on_success: never
      on_failure: always